# Generated by Django 3.1.7 on 2021-02-24 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('carNumber', models.AutoField(primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('registerNum', models.CharField(max_length=10)),
                ('year', models.PositiveSmallIntegerField(max_length=4)),
                ('powerLine', models.CharField(max_length=50)),
                ('emissions', models.PositiveSmallIntegerField(max_length=3)),
                ('seats', models.PositiveSmallIntegerField(max_length=2)),
                ('location', models.CharField(max_length=50)),
                ('carOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
