# Generated by Django 3.1.7 on 2021-02-24 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0002_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='emissions',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='seats',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
