# Generated by Django 3.1.7 on 2021-02-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0003_auto_20210224_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
