# Generated by Django 3.1.7 on 2021-02-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0004_car_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(choices=[('ferrari', 'Ferrari'), ('lamborghini', 'Lamborghini')], max_length=50),
        ),
    ]
