# Generated by Django 3.1.7 on 2021-02-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0005_auto_20210227_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(choices=[('Abarth', 'Abarth'), ('Alfa Romeo', 'Alfa Romeo'), ('Aston Martin', 'Aston Martin'), ('Audi', 'Audi'), ('Bentley', 'Bentley'), ('BMW', 'BMW')], max_length=50),
        ),
    ]
