# Generated by Django 3.1.7 on 2021-02-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0007_auto_20210227_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(choices=[('(', '('), ('(', '('), ('A', 'A'), ('b', 'b'), ('a', 'a'), ('r', 'r'), ('t', 't'), ('h', 'h'), (',', ','), ('A', 'A'), ('b', 'b'), ('a', 'a'), ('r', 'r'), ('t', 't'), ('h', 'h'), (')', ')'), (',', ','), ('\n', '\n')], max_length=50),
        ),
    ]
