# Generated by Django 3.1.7 on 2021-02-27 22:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0010_auto_20210227_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rents',
            fields=[
                ('rentNumber', models.AutoField(primary_key=True, serialize=False)),
                ('rentPrice', models.PositiveSmallIntegerField()),
                ('startDate', models.DateTimeField(default=datetime.datetime(2021, 2, 27, 22, 0, 44, 506392, tzinfo=utc))),
                ('endDate', models.DateTimeField(default=datetime.datetime(2021, 2, 28, 22, 0, 44, 506430, tzinfo=utc))),
                ('carNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentacar.car')),
                ('renteeNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentee', to=settings.AUTH_USER_MODEL)),
                ('renterNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
