# Generated by Django 3.1.7 on 2021-03-01 11:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0013_auto_20210301_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 2, 11, 41, 31, 371832, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rent',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 11, 41, 31, 371795, tzinfo=utc)),
        ),
    ]
