# Generated by Django 3.1.7 on 2021-03-01 11:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0015_auto_20210301_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 2, 11, 43, 50, 246649, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rent',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 11, 43, 50, 246612, tzinfo=utc)),
        ),
    ]
