# Generated by Django 3.1.7 on 2021-03-01 11:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0016_auto_20210301_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 2, 11, 47, 46, 312793, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rent',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 11, 47, 46, 312744, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='CarOwners',
        ),
    ]
