# Generated by Django 3.1.7 on 2021-03-01 12:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0017_auto_20210301_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carowner',
            old_name='car_id',
            new_name='car',
        ),
        migrations.RenameField(
            model_name='carowner',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='rent',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 2, 12, 27, 46, 976142, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rent',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 12, 27, 46, 976105, tzinfo=utc)),
        ),
    ]
