# Generated by Django 3.1.7 on 2021-03-01 12:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0018_auto_20210301_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 2, 12, 33, 47, 798381, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rent',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 12, 33, 47, 798345, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='CarOwner',
        ),
    ]
