# Generated by Django 3.1.7 on 2021-03-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0021_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='picture',
            field=models.ImageField(blank=True, upload_to=None),
        ),
    ]
