# Generated by Django 3.1.7 on 2021-03-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0023_auto_20210302_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images')),
            ],
            options={
                'db_table': 'rentacar_carimage',
            },
        ),
        migrations.RemoveField(
            model_name='car',
            name='picture',
        ),
    ]
