# Generated by Django 3.1.7 on 2021-03-02 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0024_auto_20210302_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carimage',
            name='title',
        ),
    ]
