# Generated by Django 3.1.7 on 2021-03-02 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0025_remove_carimage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='carimage',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rentacar.car'),
            preserve_default=False,
        ),
    ]
