# Generated by Django 3.1.7 on 2021-03-04 12:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0026_carimage_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 4, 12, 40, 37, 371030, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 4, 12, 40, 37, 370994, tzinfo=utc), null=True),
        ),
    ]
