# Generated by Django 3.1.7 on 2021-03-05 23:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0027_auto_20210304_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rent',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 5, 23, 38, 49, 619329, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 5, 23, 38, 49, 619292, tzinfo=utc), null=True),
        ),
    ]
