# Generated by Django 3.1.7 on 2021-03-06 00:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0029_auto_20210306_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 0, 17, 48, 156095, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 0, 17, 48, 156057, tzinfo=utc), null=True),
        ),
    ]
