# Generated by Django 3.1.7 on 2021-03-06 00:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0032_auto_20210306_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='owners',
        ),
        migrations.AlterField(
            model_name='rent',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 0, 47, 14, 437203, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 0, 47, 14, 437166, tzinfo=utc), null=True),
        ),
    ]
