# Generated by Django 3.1.7 on 2021-03-06 01:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0033_auto_20210306_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='addowner',
            name='requestDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 1, 57, 0, 847796, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 1, 57, 0, 849401, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 1, 57, 0, 849365, tzinfo=utc), null=True),
        ),
    ]
