# Generated by Django 3.1.7 on 2021-03-06 02:15

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0034_auto_20210306_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addowner',
            name='requestDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 2, 15, 25, 93952, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rentacar.car'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 2, 15, 25, 95854, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 2, 15, 25, 95814, tzinfo=utc), null=True),
        ),
    ]
