# Generated by Django 3.1.7 on 2021-03-06 02:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0035_auto_20210306_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='main_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='main_owner', to='rentacar.customuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addowner',
            name='requestDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 2, 53, 7, 450691, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 2, 53, 7, 452307, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 2, 53, 7, 452275, tzinfo=utc), null=True),
        ),
    ]
