# Generated by Django 3.1.7 on 2021-03-06 03:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0036_auto_20210306_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addowner',
            name='requestDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 3, 4, 24, 417066, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 3, 4, 24, 418912, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 3, 4, 24, 418880, tzinfo=utc), null=True),
        ),
    ]
