# Generated by Django 3.1.7 on 2021-03-06 23:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0037_auto_20210306_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addowner',
            name='requestDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 23, 0, 50, 636144, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 7, 23, 0, 50, 638047, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 23, 0, 50, 638010, tzinfo=utc), null=True),
        ),
    ]
