# Generated by Django 3.1.7 on 2021-03-09 18:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0038_auto_20210306_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addowner',
            name='requestDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 9, 18, 47, 26, 760595, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='endDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 10, 18, 47, 26, 762250, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='expired',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rent',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 9, 18, 47, 26, 762217, tzinfo=utc), null=True),
        ),
    ]
